version: "3"
services:
  back:
    tty: true
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back:/back
      # front:
  #   build:
  #     context: ./front
  #   volumes:
  #     - ./front:/front
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
