version: "3"
services:
  back:
    tty: true
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/back
  nginx:
    build:
      context: ./nginx
    logging:
      driver: none
    ports: 
      - '80:80'
  front:
     build:
       context: ./front
     volumes:
       - ./front:/front
       - /front/node_modules/
